apiVersion : apps/v1 
kind: Deployment
metadata:
  name: my-web-deployment-autoscaling
  labels:
    app: my-k8s-app10
    env: prod
    tier: front
    owner: ypanasiuk
spec: 
  selector: 
    matchLabels: 
      project: app10
  template:  
    metadata: 
      labels: 
        project: app10
    spec: 
      containers:
        - name: app10-cont
          image: nginx:latest
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"
          ports: 
            - containerPort: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata: 
  name: my-autoscale 
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: my-web-deployment-autoscaling
  minReplicas: 3
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
       type: Utilization
       averageUtilization: 50

